# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller 编译脚本
将 Python 后端 (FastAPI) 编译为独立的 Windows exe 可执行文件。
"""
import os
import sys

# 项目根目录
ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[os.path.dirname(os.path.abspath(__file__))],
    binaries=[],
    datas=[],
    hiddenimports=[
        # FastAPI 及相关
        'fastapi',
        'fastapi.routing',
        'fastapi.openapi',
        'fastapi.openapi.utils',
        'uvicorn',
        'uvicorn.main',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.middleware',
        'uvicorn.middleware.wsgi',
        'uvicorn.workers',
        'pydantic',
        'pydantic.fields',
        'pydantic.validators',
        'pydantic.main',
        'pydantic.generics',
        'starlette',
        'starlette.routing',
        'starlette.middleware',
        'starlette.middleware.cors',
        'starlette.staticfiles',
        'starlette.responses',
        'starlette.requests',
        'starlette.datastructures',
        'starlette.formparsers',
        # PDF 处理
        'fitz',
        'fitz.fitz',
        # OpenAI SDK
        'openai',
        'openai.resources',
        'openai.resources.chat',
        'openai.resources.chat.completions',
        'httpx',
        'httpcore',
        # 文档导出
        'docx',
        'docx.api',
        'docx.shared',
        'docx.enum',
        'docx.enum.text',
        'docx.oxml',
        'docx.oxml.ns',
        # 图片处理
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        # 其他依赖
        'dotenv',
        'multipart',
        'python_multipart',
        'yaml',
        'json',
        'hashlib',
        'base64',
        're',
        'os',
        'sys',
        'typing',
        'asyncio',
        'logging',
        'importlib',
        'importlib.metadata',
        'importlib.util',
        'concurrent',
        'concurrent.futures',
        'multiprocessing',
        'socketserver',
        'email',
        'email.mime',
        'email.mime.multipart',
        'email.mime.text',
        'email.mime.base',
        'charset_normalizer',
        'idna',
        'sniffio',
        'anyio',
        'anyio.streams',
        'anyio.streams.file',
        'anyio.from_thread',
        'certifi',
        'h11',
        'wsproto',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # 排除不需要的模块减少体积
        'tkinter',
        'matplotlib',
        'scipy',
        'sympy',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'notebook',
        'jupyter',
        'jupyter_client',
        'ipython',
        'IPython',
        'nbformat',
        'nbconvert',
        'zmq',
        'test',
        'unittest',
        'distutils',
        'setuptools',
        'wheel',
        'pip',
        'curses',
        'tcl',
        'tcl8',
        'sqlite3',
        'dbm',
        'gdbm',
        'nis',
        'ossaudiodev',
        'sndhdr',
        'spwd',
        'turtle',
        'tkinter',
        'typing_extensions._fast',
    ],
    noarchive=False,
)

# 排除不需要的 .pyc 字节码
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,          # Windows GUI 模式：不显示控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
